import { ResultSetHeader } from 'mysql2';
import { query } from '../lib/db';

export async function seedOrders() {
  console.log('Seeding sample orders...');
  
  const sampleOrders = [
    {
      head: {
        OrderDate: '11/20/2025',
        CustomerName: 'AATREYA EXPORT',
        CustomerMobileNo: '9876543210',
        PartyOrderNo: 'PO-001',
        PartyOrderDate: '11/18/2025',
        DueDate: '11/30/2025',
        Measurement: 'INCH',
        Remarks: 'Urgent order',
        TotalOrderPiece: 18500,
        TotalOrderWeight: '925.750',
        JobStatus: 'Pending',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: '1 KG PET BOX',
          Width: '12.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '185',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Standard quality',
          OrderPiece: '5000',
          OrderWeight: '245.500',
          RequiredWeight: 240.000,
          RateFor: 'PIECE',
          Rate: '5.50',
        },
        {
          Sno: 2,
          ProductName: 'BLACK LDPE POLYBAG',
          Width: '10.00',
          Length: '12.00',
          Flop: '3.00',
          Gauge: '150',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '4500',
          OrderWeight: '220.250',
          RequiredWeight: 215.000,
          RateFor: 'WEIGHT',
          Rate: '120.00',
        },
        {
          Sno: 3,
          ProductName: 'TRANSPARENT POLYBAG',
          Width: '8.00',
          Length: '10.00',
          Flop: '2.00',
          Gauge: '120',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Food grade',
          OrderPiece: '6000',
          OrderWeight: '285.000',
          RequiredWeight: 275.000,
          RateFor: 'PIECE',
          Rate: '3.25',
        },
        {
          Sno: 4,
          ProductName: 'WHITE LDPE POLYBAG',
          Width: '9.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '140',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '3000',
          OrderWeight: '175.000',
          RequiredWeight: 170.000,
          RateFor: 'PIECE',
          Rate: '4.20',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/21/2025',
        CustomerName: 'FABRIC SOLUTIONS INC',
        CustomerMobileNo: '9876543212',
        PartyOrderNo: 'PO-002',
        PartyOrderDate: '11/19/2025',
        DueDate: '12/05/2025',
        Measurement: 'CM',
        Remarks: 'Premium quality required',
        TotalOrderPiece: 26500,
        TotalOrderWeight: '1325.500',
        JobStatus: 'In Progress',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: '3 COLOUR PRINTED BAG',
          Width: '15.00',
          Length: '20.00',
          Flop: '2.00',
          Gauge: '200',
          NoOfBackColors: '1',
          NoOfFrontColors: '2',
          Remarks: 'Custom design',
          OrderPiece: '8000',
          OrderWeight: '420.500',
          RequiredWeight: 410.000,
          RateFor: 'PIECE',
          Rate: '8.75',
        },
        {
          Sno: 2,
          ProductName: '2 COLOUR PRINTED BAG',
          Width: '12.00',
          Length: '14.00',
          Flop: '2.00',
          Gauge: '160',
          NoOfBackColors: '1',
          NoOfFrontColors: '1',
          Remarks: 'Logo printing',
          OrderPiece: '7000',
          OrderWeight: '335.250',
          RequiredWeight: 325.000,
          RateFor: 'PIECE',
          Rate: '6.50',
        },
        {
          Sno: 3,
          ProductName: 'BLUE LDPE POLYBAG',
          Width: '11.00',
          Length: '13.00',
          Flop: '2.00',
          Gauge: '155',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Blue color',
          OrderPiece: '6500',
          OrderWeight: '310.750',
          RequiredWeight: 300.000,
          RateFor: 'PIECE',
          Rate: '4.95',
        },
        {
          Sno: 4,
          ProductName: 'GREEN LDPE POLYBAG',
          Width: '10.00',
          Length: '12.00',
          Flop: '2.00',
          Gauge: '145',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Eco branding',
          OrderPiece: '5000',
          OrderWeight: '259.000',
          RequiredWeight: 250.000,
          RateFor: 'PIECE',
          Rate: '5.10',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/22/2025',
        CustomerName: 'SEEERS PACKAGING',
        CustomerMobileNo: '9876543213',
        PartyOrderNo: 'PO-003',
        PartyOrderDate: '11/20/2025',
        DueDate: '12/10/2025',
        Measurement: 'INCH',
        Remarks: 'Bulk order for retail',
        TotalOrderPiece: 32000,
        TotalOrderWeight: '1580.500',
        JobStatus: 'Pending',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'TRANSPARENT POLYBAG',
          Width: '8.00',
          Length: '10.00',
          Flop: '2.00',
          Gauge: '120',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Food grade quality',
          OrderPiece: '8000',
          OrderWeight: '385.500',
          RequiredWeight: 375.000,
          RateFor: 'PIECE',
          Rate: '3.25',
        },
        {
          Sno: 2,
          ProductName: 'RED LDPE POLYBAG',
          Width: '9.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '145',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Festive packaging',
          OrderPiece: '7000',
          OrderWeight: '340.250',
          RequiredWeight: 330.000,
          RateFor: 'PIECE',
          Rate: '5.10',
        },
        {
          Sno: 3,
          ProductName: 'YELLOW LDPE POLYBAG',
          Width: '10.00',
          Length: '14.00',
          Flop: '2.00',
          Gauge: '175',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Bright yellow',
          OrderPiece: '9000',
          OrderWeight: '435.500',
          RequiredWeight: 420.000,
          RateFor: 'PIECE',
          Rate: '5.60',
        },
        {
          Sno: 4,
          ProductName: '1 KG PET BOX',
          Width: '12.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '185',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '8000',
          OrderWeight: '419.250',
          RequiredWeight: 410.000,
          RateFor: 'WEIGHT',
          Rate: '125.00',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/22/2025',
        CustomerName: 'GLOBAL TRADERS',
        CustomerMobileNo: '9876543214',
        PartyOrderNo: 'PO-004',
        PartyOrderDate: '11/21/2025',
        DueDate: '12/01/2025',
        Measurement: 'CM',
        Remarks: 'Express delivery required',
        TotalOrderPiece: 22500,
        TotalOrderWeight: '1145.750',
        JobStatus: 'In Progress',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: '5 KG PET BOX',
          Width: '18.00',
          Length: '15.00',
          Flop: '3.00',
          Gauge: '220',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Heavy duty',
          OrderPiece: '5000',
          OrderWeight: '265.500',
          RequiredWeight: 255.000,
          RateFor: 'WEIGHT',
          Rate: '135.00',
        },
        {
          Sno: 2,
          ProductName: '3 KG PET BOX',
          Width: '15.00',
          Length: '13.00',
          Flop: '2.00',
          Gauge: '195',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Medium size',
          OrderPiece: '6000',
          OrderWeight: '310.250',
          RequiredWeight: 300.000,
          RateFor: 'WEIGHT',
          Rate: '128.00',
        },
        {
          Sno: 3,
          ProductName: 'ZIPPER POLYBAG',
          Width: '20.00',
          Length: '25.00',
          Flop: '1.00',
          Gauge: '200',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'With zipper lock',
          OrderPiece: '5500',
          OrderWeight: '285.000',
          RequiredWeight: 275.000,
          RateFor: 'PIECE',
          Rate: '12.50',
        },
        {
          Sno: 4,
          ProductName: '4 COLOUR PRINTED BAG',
          Width: '16.00',
          Length: '18.00',
          Flop: '2.00',
          Gauge: '190',
          NoOfBackColors: '2',
          NoOfFrontColors: '2',
          Remarks: 'Full color printing',
          OrderPiece: '6000',
          OrderWeight: '285.000',
          RequiredWeight: 275.000,
          RateFor: 'PIECE',
          Rate: '10.25',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/23/2025',
        CustomerName: 'METRO SUPPLIES',
        CustomerMobileNo: '9876543215',
        PartyOrderNo: 'PO-005',
        PartyOrderDate: '11/22/2025',
        DueDate: '12/15/2025',
        Measurement: 'INCH',
        Remarks: 'Standard packaging',
        TotalOrderPiece: 24500,
        TotalOrderWeight: '1215.500',
        JobStatus: 'Completed',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'WHITE LDPE POLYBAG',
          Width: '14.00',
          Length: '16.00',
          Flop: '2.00',
          Gauge: '180',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '7000',
          OrderWeight: '320.500',
          RequiredWeight: 310.000,
          RateFor: 'PIECE',
          Rate: '4.80',
        },
        {
          Sno: 2,
          ProductName: '2 COLOUR PRINTED BAG',
          Width: '12.00',
          Length: '14.00',
          Flop: '2.00',
          Gauge: '160',
          NoOfBackColors: '1',
          NoOfFrontColors: '1',
          Remarks: 'Logo printing',
          OrderPiece: '5000',
          OrderWeight: '260.250',
          RequiredWeight: 250.000,
          RateFor: 'PIECE',
          Rate: '6.50',
        },
        {
          Sno: 3,
          ProductName: 'CLEAR POLYBAG',
          Width: '7.00',
          Length: '9.00',
          Flop: '2.00',
          Gauge: '110',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Crystal clear',
          OrderPiece: '6500',
          OrderWeight: '315.250',
          RequiredWeight: 305.000,
          RateFor: 'WEIGHT',
          Rate: '115.00',
        },
        {
          Sno: 4,
          ProductName: 'BIODEGRADABLE POLYBAG',
          Width: '10.00',
          Length: '12.00',
          Flop: '2.00',
          Gauge: '140',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Eco-friendly material',
          OrderPiece: '6000',
          OrderWeight: '319.500',
          RequiredWeight: 310.000,
          RateFor: 'WEIGHT',
          Rate: '145.00',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/23/2025',
        CustomerName: 'SUNRISE INDUSTRIES',
        CustomerMobileNo: '9876543216',
        PartyOrderNo: 'PO-006',
        PartyOrderDate: '11/22/2025',
        DueDate: '12/08/2025',
        Measurement: 'CM',
        Remarks: 'Quality check required',
        TotalOrderPiece: 21500,
        TotalOrderWeight: '1085.750',
        JobStatus: 'Pending',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'ZIPPER POLYBAG',
          Width: '20.00',
          Length: '25.00',
          Flop: '1.00',
          Gauge: '200',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'With zipper lock',
          OrderPiece: '6000',
          OrderWeight: '310.250',
          RequiredWeight: 300.000,
          RateFor: 'PIECE',
          Rate: '12.50',
        },
        {
          Sno: 2,
          ProductName: 'SILVER PRINTED BAG',
          Width: '13.00',
          Length: '16.00',
          Flop: '2.00',
          Gauge: '180',
          NoOfBackColors: '',
          NoOfFrontColors: '1',
          Remarks: 'Silver foil',
          OrderPiece: '5500',
          OrderWeight: '275.500',
          RequiredWeight: 265.000,
          RateFor: 'PIECE',
          Rate: '8.90',
        },
        {
          Sno: 3,
          ProductName: '2 KG PET BOX',
          Width: '14.00',
          Length: '12.00',
          Flop: '2.00',
          Gauge: '190',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '5000',
          OrderWeight: '250.000',
          RequiredWeight: 240.000,
          RateFor: 'WEIGHT',
          Rate: '125.00',
        },
        {
          Sno: 4,
          ProductName: 'GOLD PRINTED BAG',
          Width: '12.00',
          Length: '15.00',
          Flop: '2.00',
          Gauge: '170',
          NoOfBackColors: '',
          NoOfFrontColors: '1',
          Remarks: 'Gold foil print',
          OrderPiece: '5000',
          OrderWeight: '250.000',
          RequiredWeight: 240.000,
          RateFor: 'PIECE',
          Rate: '9.50',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/24/2025',
        CustomerName: 'PACIFIC EXPORTS',
        CustomerMobileNo: '9876543217',
        PartyOrderNo: 'PO-007',
        PartyOrderDate: '11/23/2025',
        DueDate: '12/20/2025',
        Measurement: 'INCH',
        Remarks: 'Export quality',
        TotalOrderPiece: 35000,
        TotalOrderWeight: '1735.500',
        JobStatus: 'In Progress',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'BIODEGRADABLE POLYBAG',
          Width: '10.00',
          Length: '12.00',
          Flop: '2.00',
          Gauge: '140',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Eco-friendly material',
          OrderPiece: '9000',
          OrderWeight: '445.500',
          RequiredWeight: 430.000,
          RateFor: 'WEIGHT',
          Rate: '145.00',
        },
        {
          Sno: 2,
          ProductName: '10 KG PET BOX',
          Width: '22.00',
          Length: '18.00',
          Flop: '3.00',
          Gauge: '250',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Extra heavy duty',
          OrderPiece: '8000',
          OrderWeight: '420.000',
          RequiredWeight: 410.000,
          RateFor: 'WEIGHT',
          Rate: '155.00',
        },
        {
          Sno: 3,
          ProductName: '5 COLOUR PRINTED BAG',
          Width: '14.00',
          Length: '17.00',
          Flop: '2.00',
          Gauge: '185',
          NoOfBackColors: '2',
          NoOfFrontColors: '3',
          Remarks: 'Multi-color design',
          OrderPiece: '10000',
          OrderWeight: '485.000',
          RequiredWeight: 470.000,
          RateFor: 'PIECE',
          Rate: '11.75',
        },
        {
          Sno: 4,
          ProductName: 'WHITE LDPE POLYBAG',
          Width: '14.00',
          Length: '16.00',
          Flop: '2.00',
          Gauge: '180',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '8000',
          OrderWeight: '385.000',
          RequiredWeight: 375.000,
          RateFor: 'PIECE',
          Rate: '4.80',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/24/2025',
        CustomerName: 'ROYAL PACKAGING',
        CustomerMobileNo: '9876543218',
        PartyOrderNo: 'PO-008',
        PartyOrderDate: '11/23/2025',
        DueDate: '12/12/2025',
        Measurement: 'CM',
        Remarks: 'Premium finish required',
        TotalOrderPiece: 28500,
        TotalOrderWeight: '1425.750',
        JobStatus: 'Pending',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: '4 COLOUR PRINTED BAG',
          Width: '16.00',
          Length: '18.00',
          Flop: '2.00',
          Gauge: '190',
          NoOfBackColors: '2',
          NoOfFrontColors: '2',
          Remarks: 'Full color printing',
          OrderPiece: '9000',
          OrderWeight: '465.750',
          RequiredWeight: 450.000,
          RateFor: 'PIECE',
          Rate: '10.25',
        },
        {
          Sno: 2,
          ProductName: '3 COLOUR PRINTED BAG',
          Width: '15.00',
          Length: '20.00',
          Flop: '2.00',
          Gauge: '200',
          NoOfBackColors: '1',
          NoOfFrontColors: '2',
          Remarks: 'Custom design',
          OrderPiece: '7500',
          OrderWeight: '380.000',
          RequiredWeight: 370.000,
          RateFor: 'PIECE',
          Rate: '8.75',
        },
        {
          Sno: 3,
          ProductName: 'TRANSPARENT POLYBAG',
          Width: '8.00',
          Length: '10.00',
          Flop: '2.00',
          Gauge: '120',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Food grade',
          OrderPiece: '6000',
          OrderWeight: '295.000',
          RequiredWeight: 285.000,
          RateFor: 'PIECE',
          Rate: '3.25',
        },
        {
          Sno: 4,
          ProductName: 'BLACK LDPE POLYBAG',
          Width: '10.00',
          Length: '12.00',
          Flop: '3.00',
          Gauge: '150',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '6000',
          OrderWeight: '285.000',
          RequiredWeight: 275.000,
          RateFor: 'WEIGHT',
          Rate: '120.00',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/25/2025',
        CustomerName: 'DIAMOND TRADERS',
        CustomerMobileNo: '9876543219',
        PartyOrderNo: 'PO-009',
        PartyOrderDate: '11/24/2025',
        DueDate: '12/18/2025',
        Measurement: 'INCH',
        Remarks: 'Regular customer order',
        TotalOrderPiece: 26000,
        TotalOrderWeight: '1295.500',
        JobStatus: 'Completed',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'BLUE LDPE POLYBAG',
          Width: '11.00',
          Length: '13.00',
          Flop: '2.00',
          Gauge: '155',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Blue color',
          OrderPiece: '11000',
          OrderWeight: '535.250',
          RequiredWeight: 520.000,
          RateFor: 'PIECE',
          Rate: '4.95',
        },
        {
          Sno: 2,
          ProductName: 'GREEN LDPE POLYBAG',
          Width: '13.00',
          Length: '15.00',
          Flop: '2.00',
          Gauge: '165',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Eco branding',
          OrderPiece: '6500',
          OrderWeight: '320.250',
          RequiredWeight: 310.000,
          RateFor: 'PIECE',
          Rate: '5.35',
        },
        {
          Sno: 3,
          ProductName: 'RED LDPE POLYBAG',
          Width: '9.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '145',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Festive packaging',
          OrderPiece: '5000',
          OrderWeight: '245.000',
          RequiredWeight: 235.000,
          RateFor: 'PIECE',
          Rate: '5.10',
        },
        {
          Sno: 4,
          ProductName: '2 COLOUR PRINTED BAG',
          Width: '12.00',
          Length: '14.00',
          Flop: '2.00',
          Gauge: '160',
          NoOfBackColors: '1',
          NoOfFrontColors: '1',
          Remarks: 'Logo printing',
          OrderPiece: '3500',
          OrderWeight: '195.000',
          RequiredWeight: 185.000,
          RateFor: 'PIECE',
          Rate: '6.50',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/25/2025',
        CustomerName: 'APEX SOLUTIONS',
        CustomerMobileNo: '9876543220',
        PartyOrderNo: 'PO-010',
        PartyOrderDate: '11/24/2025',
        DueDate: '12/06/2025',
        Measurement: 'CM',
        Remarks: 'Rush order',
        TotalOrderPiece: 24000,
        TotalOrderWeight: '1195.500',
        JobStatus: 'In Progress',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: '3 KG PET BOX',
          Width: '15.00',
          Length: '13.00',
          Flop: '2.00',
          Gauge: '195',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Medium size',
          OrderPiece: '7500',
          OrderWeight: '385.500',
          RequiredWeight: 370.000,
          RateFor: 'WEIGHT',
          Rate: '128.00',
        },
        {
          Sno: 2,
          ProductName: '1 KG PET BOX',
          Width: '12.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '185',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Standard quality',
          OrderPiece: '5500',
          OrderWeight: '270.000',
          RequiredWeight: 260.000,
          RateFor: 'PIECE',
          Rate: '5.50',
        },
        {
          Sno: 3,
          ProductName: 'ZIPPER POLYBAG',
          Width: '20.00',
          Length: '25.00',
          Flop: '1.00',
          Gauge: '200',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'With zipper lock',
          OrderPiece: '6000',
          OrderWeight: '295.000',
          RequiredWeight: 285.000,
          RateFor: 'PIECE',
          Rate: '12.50',
        },
        {
          Sno: 4,
          ProductName: 'YELLOW LDPE POLYBAG',
          Width: '10.00',
          Length: '14.00',
          Flop: '2.00',
          Gauge: '175',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Bright yellow',
          OrderPiece: '5000',
          OrderWeight: '245.000',
          RequiredWeight: 235.000,
          RateFor: 'PIECE',
          Rate: '5.60',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/26/2025',
        CustomerName: 'ZENITH ENTERPRISES',
        CustomerMobileNo: '9876543221',
        PartyOrderNo: 'PO-011',
        PartyOrderDate: '11/25/2025',
        DueDate: '12/22/2025',
        Measurement: 'INCH',
        Remarks: 'Seasonal order',
        TotalOrderPiece: 27500,
        TotalOrderWeight: '1365.750',
        JobStatus: 'Pending',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'RED LDPE POLYBAG',
          Width: '9.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '145',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Festive packaging',
          OrderPiece: '10000',
          OrderWeight: '460.500',
          RequiredWeight: 445.000,
          RateFor: 'PIECE',
          Rate: '5.10',
        },
        {
          Sno: 2,
          ProductName: 'GOLD PRINTED BAG',
          Width: '12.00',
          Length: '15.00',
          Flop: '2.00',
          Gauge: '170',
          NoOfBackColors: '',
          NoOfFrontColors: '1',
          Remarks: 'Gold foil print',
          OrderPiece: '8000',
          OrderWeight: '365.250',
          RequiredWeight: 350.000,
          RateFor: 'PIECE',
          Rate: '9.50',
        },
        {
          Sno: 3,
          ProductName: 'WHITE LDPE POLYBAG',
          Width: '14.00',
          Length: '16.00',
          Flop: '2.00',
          Gauge: '180',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '5000',
          OrderWeight: '245.000',
          RequiredWeight: 235.000,
          RateFor: 'PIECE',
          Rate: '4.80',
        },
        {
          Sno: 4,
          ProductName: 'CLEAR POLYBAG',
          Width: '7.00',
          Length: '9.00',
          Flop: '2.00',
          Gauge: '110',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Crystal clear',
          OrderPiece: '4500',
          OrderWeight: '230.000',
          RequiredWeight: 220.000,
          RateFor: 'WEIGHT',
          Rate: '115.00',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/26/2025',
        CustomerName: 'OMEGA PACKAGING',
        CustomerMobileNo: '9876543222',
        PartyOrderNo: 'PO-012',
        PartyOrderDate: '11/25/2025',
        DueDate: '12/14/2025',
        Measurement: 'CM',
        Remarks: 'Standard specifications',
        TotalOrderPiece: 30000,
        TotalOrderWeight: '1485.250',
        JobStatus: 'In Progress',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'GREEN LDPE POLYBAG',
          Width: '13.00',
          Length: '15.00',
          Flop: '2.00',
          Gauge: '165',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Eco branding',
          OrderPiece: '13000',
          OrderWeight: '645.250',
          RequiredWeight: 625.000,
          RateFor: 'PIECE',
          Rate: '5.35',
        },
        {
          Sno: 2,
          ProductName: 'BLUE LDPE POLYBAG',
          Width: '11.00',
          Length: '13.00',
          Flop: '2.00',
          Gauge: '155',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Blue color',
          OrderPiece: '6000',
          OrderWeight: '295.000',
          RequiredWeight: 285.000,
          RateFor: 'PIECE',
          Rate: '4.95',
        },
        {
          Sno: 3,
          ProductName: 'YELLOW LDPE POLYBAG',
          Width: '10.00',
          Length: '14.00',
          Flop: '2.00',
          Gauge: '175',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Bright yellow',
          OrderPiece: '6000',
          OrderWeight: '295.000',
          RequiredWeight: 285.000,
          RateFor: 'PIECE',
          Rate: '5.60',
        },
        {
          Sno: 4,
          ProductName: 'TRANSPARENT POLYBAG',
          Width: '8.00',
          Length: '10.00',
          Flop: '2.00',
          Gauge: '120',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Food grade',
          OrderPiece: '5000',
          OrderWeight: '250.000',
          RequiredWeight: 240.000,
          RateFor: 'PIECE',
          Rate: '3.25',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/27/2025',
        CustomerName: 'STELLAR INDUSTRIES',
        CustomerMobileNo: '9876543223',
        PartyOrderNo: 'PO-013',
        PartyOrderDate: '11/26/2025',
        DueDate: '12/25/2025',
        Measurement: 'INCH',
        Remarks: 'Year-end bulk order',
        TotalOrderPiece: 25000,
        TotalOrderWeight: '1150.500',
        JobStatus: 'Pending',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'CLEAR POLYBAG',
          Width: '7.00',
          Length: '9.00',
          Flop: '2.00',
          Gauge: '110',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Crystal clear',
          OrderPiece: '25000',
          OrderWeight: '1150.500',
          RequiredWeight: 1100.000,
          RateFor: 'WEIGHT',
          Rate: '115.00',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/27/2025',
        CustomerName: 'PRIME EXPORTS',
        CustomerMobileNo: '9876543224',
        PartyOrderNo: 'PO-014',
        PartyOrderDate: '11/26/2025',
        DueDate: '12/09/2025',
        Measurement: 'CM',
        Remarks: 'International shipping',
        TotalOrderPiece: 14000,
        TotalOrderWeight: '715.750',
        JobStatus: 'Completed',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: '10 KG PET BOX',
          Width: '22.00',
          Length: '18.00',
          Flop: '3.00',
          Gauge: '250',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Extra heavy duty',
          OrderPiece: '14000',
          OrderWeight: '715.750',
          RequiredWeight: 690.000,
          RateFor: 'WEIGHT',
          Rate: '155.00',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/28/2025',
        CustomerName: 'VERTEX PACKAGING',
        CustomerMobileNo: '9876543225',
        PartyOrderNo: 'PO-015',
        PartyOrderDate: '11/27/2025',
        DueDate: '12/16/2025',
        Measurement: 'INCH',
        Remarks: 'Custom size order',
        TotalOrderPiece: 29000,
        TotalOrderWeight: '1425.250',
        JobStatus: 'In Progress',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'YELLOW LDPE POLYBAG',
          Width: '10.00',
          Length: '14.00',
          Flop: '2.00',
          Gauge: '175',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Bright yellow',
          OrderPiece: '9000',
          OrderWeight: '435.500',
          RequiredWeight: 420.000,
          RateFor: 'PIECE',
          Rate: '5.60',
        },
        {
          Sno: 2,
          ProductName: '5 COLOUR PRINTED BAG',
          Width: '14.00',
          Length: '17.00',
          Flop: '2.00',
          Gauge: '185',
          NoOfBackColors: '2',
          NoOfFrontColors: '3',
          Remarks: 'Multi-color design',
          OrderPiece: '7000',
          OrderWeight: '344.750',
          RequiredWeight: 330.000,
          RateFor: 'PIECE',
          Rate: '11.75',
        },
        {
          Sno: 3,
          ProductName: 'BLACK LDPE POLYBAG',
          Width: '10.00',
          Length: '12.00',
          Flop: '3.00',
          Gauge: '150',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '7000',
          OrderWeight: '340.000',
          RequiredWeight: 330.000,
          RateFor: 'WEIGHT',
          Rate: '120.00',
        },
        {
          Sno: 4,
          ProductName: '3 COLOUR PRINTED BAG',
          Width: '15.00',
          Length: '20.00',
          Flop: '2.00',
          Gauge: '200',
          NoOfBackColors: '1',
          NoOfFrontColors: '2',
          Remarks: 'Custom design',
          OrderPiece: '6000',
          OrderWeight: '305.000',
          RequiredWeight: 295.000,
          RateFor: 'PIECE',
          Rate: '8.75',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/28/2025',
        CustomerName: 'NEXUS TRADERS',
        CustomerMobileNo: '9876543226',
        PartyOrderNo: 'PO-016',
        PartyOrderDate: '11/27/2025',
        DueDate: '12/11/2025',
        Measurement: 'CM',
        Remarks: 'Repeat order',
        TotalOrderPiece: 26500,
        TotalOrderWeight: '1315.500',
        JobStatus: 'Pending',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: 'SILVER PRINTED BAG',
          Width: '13.00',
          Length: '16.00',
          Flop: '2.00',
          Gauge: '180',
          NoOfBackColors: '',
          NoOfFrontColors: '1',
          Remarks: 'Silver foil',
          OrderPiece: '10500',
          OrderWeight: '525.500',
          RequiredWeight: 510.000,
          RateFor: 'PIECE',
          Rate: '8.90',
        },
        {
          Sno: 2,
          ProductName: 'GOLD PRINTED BAG',
          Width: '12.00',
          Length: '15.00',
          Flop: '2.00',
          Gauge: '170',
          NoOfBackColors: '',
          NoOfFrontColors: '1',
          Remarks: 'Gold foil print',
          OrderPiece: '6000',
          OrderWeight: '295.000',
          RequiredWeight: 285.000,
          RateFor: 'PIECE',
          Rate: '9.50',
        },
        {
          Sno: 3,
          ProductName: '2 KG PET BOX',
          Width: '14.00',
          Length: '12.00',
          Flop: '2.00',
          Gauge: '190',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '5500',
          OrderWeight: '270.000',
          RequiredWeight: 260.000,
          RateFor: 'WEIGHT',
          Rate: '125.00',
        },
        {
          Sno: 4,
          ProductName: 'BIODEGRADABLE POLYBAG',
          Width: '10.00',
          Length: '12.00',
          Flop: '2.00',
          Gauge: '140',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Eco-friendly material',
          OrderPiece: '4500',
          OrderWeight: '225.000',
          RequiredWeight: 215.000,
          RateFor: 'WEIGHT',
          Rate: '145.00',
        },
      ],
    },
    {
      head: {
        OrderDate: '11/29/2025',
        CustomerName: 'INFINITY SUPPLIES',
        CustomerMobileNo: '9876543227',
        PartyOrderNo: 'PO-017',
        PartyOrderDate: '11/28/2025',
        DueDate: '12/28/2025',
        Measurement: 'INCH',
        Remarks: 'New customer trial order',
        TotalOrderPiece: 19500,
        TotalOrderWeight: '965.750',
        JobStatus: 'Pending',
        ModuleEntryCode: 'TRANS-ORDER',
        CompanyId: 1,
        FinancialPeriod: '25-26',
        UserId_UserHead: 15,
      },
      details: [
        {
          Sno: 1,
          ProductName: '2 KG PET BOX',
          Width: '14.00',
          Length: '12.00',
          Flop: '2.00',
          Gauge: '190',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Sample order',
          OrderPiece: '5500',
          OrderWeight: '275.750',
          RequiredWeight: 265.000,
          RateFor: 'WEIGHT',
          Rate: '125.00',
        },
        {
          Sno: 2,
          ProductName: '1 KG PET BOX',
          Width: '12.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '185',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Standard quality',
          OrderPiece: '5000',
          OrderWeight: '245.000',
          RequiredWeight: 235.000,
          RateFor: 'PIECE',
          Rate: '5.50',
        },
        {
          Sno: 3,
          ProductName: 'TRANSPARENT POLYBAG',
          Width: '8.00',
          Length: '10.00',
          Flop: '2.00',
          Gauge: '120',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: 'Food grade quality',
          OrderPiece: '5000',
          OrderWeight: '240.000',
          RequiredWeight: 230.000,
          RateFor: 'PIECE',
          Rate: '3.25',
        },
        {
          Sno: 4,
          ProductName: 'WHITE LDPE POLYBAG',
          Width: '9.00',
          Length: '11.00',
          Flop: '2.00',
          Gauge: '140',
          NoOfBackColors: '',
          NoOfFrontColors: '',
          Remarks: '',
          OrderPiece: '4000',
          OrderWeight: '205.000',
          RequiredWeight: 195.000,
          RateFor: 'PIECE',
          Rate: '4.20',
        },
      ],
    },
  ];

  for (const order of sampleOrders) {
    try {
      // Insert order head
      const result = await query<ResultSetHeader>(
        `INSERT INTO order_head (OrderDate, CustomerName, CustomerMobileNo, PartyOrderNo, 
         PartyOrderDate, DueDate, Measurement, Remarks, TotalOrderPiece, TotalOrderWeight, 
         JobStatus, ModuleEntryCode, CompanyId, FinancialPeriod, UserId_UserHead) 
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          order.head.OrderDate,
          order.head.CustomerName,
          order.head.CustomerMobileNo,
          order.head.PartyOrderNo,
          order.head.PartyOrderDate,
          order.head.DueDate,
          order.head.Measurement,
          order.head.Remarks,
          order.head.TotalOrderPiece,
          order.head.TotalOrderWeight,
          order.head.JobStatus,
          order.head.ModuleEntryCode,
          order.head.CompanyId,
          order.head.FinancialPeriod,
          order.head.UserId_UserHead,
        ]
      );

      const orderNo = result.insertId;

      // Insert order details
      for (const detail of order.details) {
        await query(
          `INSERT INTO order_detail (OrderNo, Sno, ProductName, Width, Length, Flop, Gauge, 
           NoOfBackColors, NoOfFrontColors, Remarks, OrderPiece, OrderWeight, RequiredWeight, 
           RateFor, Rate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          [
            orderNo,
            detail.Sno,
            detail.ProductName,
            detail.Width,
            detail.Length,
            detail.Flop,
            detail.Gauge,
            detail.NoOfBackColors,
            detail.NoOfFrontColors,
            detail.Remarks,
            detail.OrderPiece,
            detail.OrderWeight,
            detail.RequiredWeight,
            detail.RateFor,
            detail.Rate,
          ]
        );
      }

      console.log(`✓ Created order ${orderNo} for ${order.head.CustomerName}`);
    } catch (error) {
      console.error(`Error inserting order for ${order.head.CustomerName}:`, error);
    }
  }

  console.log(`✓ Seeded ${sampleOrders.length} sample orders`);
}
